In [ ]:
import pandas as pd
from google.colab import files, drive

In [ ]:
uploaded = files.upload()
data = pd.read_csv('datapreprocessed.csv', index_col=0)



# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in 'label'. 
print(data['label'].unique())
data['label']= label_encoder.fit_transform(data['label']) 
data['label'].unique()

Saving datapreprocessed.csv to datapreprocessed (1).csv
['real' 'fake']


array([1, 0])

In [ ]:
import numpy as np

df1 = data[data.isna().any(axis=1)]

print(df1)
data = data.dropna()



        label text
6           1  NaN
34          1  NaN
1579        1  NaN
3365        1  NaN
3490        1  NaN
...       ...  ...
250791      0  NaN
250793      0  NaN
250859      0  NaN
250889      0  NaN
250894      0  NaN

[561 rows x 2 columns]


In [ ]:
data[:2]


label                                               text
0      1  coronavirus immunity certificate u may start i...
1      1  oluafolabi coronavirus presence corrosive anoi...

In [ ]:
#vectorization
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

x = data['text'].tolist()
y = data['label'].tolist()
x_train, x_test = train_test_split(x, test_size=0.30, random_state=1000)
Y_train, Y_test = train_test_split(y, test_size=0.30, random_state=1000)

vectorizer = CountVectorizer()
vectorizer.fit (x_train)
X_train = vectorizer.transform(x_train)
X_test  = vectorizer.transform(x_test)

Y_train = np.array(Y_train)
Y_test = np.array(Y_test)

In [ ]:
#KNN classifier

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=2)
model.fit(X_train, Y_train) 
model_predictions = model.predict(X_test)
print("\n---------KNN classifier---------")
print("\nConfusion matrix: \n", confusion_matrix(Y_test,model_predictions))
print("\nClassification Report: \n", classification_report(Y_test,model_predictions))
print("\nClassification accuracy: " ,accuracy_score(Y_test, model_predictions) * 100, "%.\n")
#results.append(accuracy_score(Y_test, model_predictions))
#models.append('KNN')


---------KNN classifier---------

Confusion matrix: 
 [[ 2882   993]
 [ 2615 69084]]

Classification Report: 
               precision    recall  f1-score   support

           0       0.52      0.74      0.62      3875
           1       0.99      0.96      0.97     71699

    accuracy                           0.95     75574
   macro avg       0.76      0.85      0.79     75574
weighted avg       0.96      0.95      0.96     75574


Classification accuracy:  95.22587133141027 %.



In [ ]:
#Random Forest
 
from sklearn.ensemble import RandomForestClassifier
modelrf = RandomForestClassifier(n_estimators=1000, random_state=0) 
modelrf.fit(X_train, Y_train)
modelrf_predictions = modelrf.predict(X_test)


#print values
print("\n---------Random Forest Classifiers---------")
print("\nConfusion matrix: \n", confusion_matrix(Y_test,modelrf_predictions))
print("\nClassification Report: \n", classification_report(Y_test,modelrf_predictions))
print("\nClassification accuracy: " ,accuracy_score(Y_test, modelrf_predictions) * 100, "%.\n")



---------Random Forest Classifiers---------

Confusion matrix: 
 [[ 3017   858]
 [   78 71621]]

Classification Report: 
               precision    recall  f1-score   support

           0       0.97      0.78      0.87      3875
           1       0.99      1.00      0.99     71699

    accuracy                           0.99     75574
   macro avg       0.98      0.89      0.93     75574
weighted avg       0.99      0.99      0.99     75574


Classification accuracy:  98.76147881546564 %.



In [ ]:
#SVM
from sklearn import svm
from sklearn.svm import SVC
modelsvm = svm.SVC(C = 1.0, kernel = 'linear', degree = 3, gamma= 'auto')
modelsvm.fit(X_train, Y_train)
modelsvm_predictions = modelsvm.predict(X_test)

#print values
print("\n---------Support Vector Machine---------")
print("\nConfusion matrix: \n", confusion_matrix(Y_test,modelsvm_predictions))
print("\nClassification Report: \n", classification_report(Y_test,modelsvm_predictions))
print("\nClassification accuracy: " ,accuracy_score(Y_test, modelsvm_predictions) * 100, "%.\n")




---------Support Vector Machine---------

Confusion matrix: 
 [[ 3112   763]
 [  307 71392]]

Classification Report: 
               precision    recall  f1-score   support

           0       0.91      0.80      0.85      3875
           1       0.99      1.00      0.99     71699

    accuracy                           0.99     75574
   macro avg       0.95      0.90      0.92     75574
weighted avg       0.99      0.99      0.99     75574


Classification accuracy:  98.58416915870536 %.

